### PR TITLE
incorporate the Team API data into the ZAP pipeline

### PR DESCRIPTION
**Pull request by afeld**
This pull request introduces a `filter-team-data` task, which takes the raw output from https://team-api.18f.gov/public/api/projects/, filters it to only the `name`s listed in the `targets.json`, and normalizes the `links`. This task, along with `fetch-team-data`, is now used in both pipelines.

Because the projects listed in `targets.json` haven't changed, this refactor doesn't actually change any behavior from our current pipelines, but makes it easy to whitelist new projects that we want to pull from the Team API.

### CODE REVIEW

**Comment by DavidEBest** [comment]
This is great! I like the approach, and I hope we can pull more data out of the team api in the future.

**Comment by ctro** [comment]
:100: This looks super. 

I like the `README` in each task dir. 
The minitest specs read nicely.  Should we make that a CT "default"?  And, was minitest/spec up to the job?

**Comment by DavidEBest** [comment]
I concur, the README is helpful. Is there a preferred way to canonize that process, like in the CONTRIBUTING.md file, maybe? Or is that unnecessary?

**Comment by afeld** [comment]
Thanks fellas!

This pull request reminds me of that quote...goes something like "Change one line, get ten comments. Change one thousand lines, get one comment." :smirk:

> I like the `README` in each task dir...Is there a preferred way to canonize that process

I tried to indicate that here:

https://github.com/18F/concourse-compliance-testing/pull/20/files#diff-04c6e90faac2675aa89e2176d2eec7d8L16

but we can be even more explicit if y'all like.

> The minitest specs read nicely. Should we make that a CT "default"?

I prefer being able to write in sentences, so works for me!

> was minitest/spec up to the job?

Yep! I have almost always used RSpec in the past (I like the hooks, matchers, and documentation better), but do like that Minitest is usable without additional dependencies. Fine to go along with this, especially since we should be keeping individual tasks small, so the test suites should be equally simple.

**Pull request merged**
